### ISSUE TITLE
Mediation Fees

### ISSUE THREAD

**Issue by palango** [raiden-network/spec#10]
The spec for the core protocol currently doesn't mention fees. We should spec out how fees work at protocol level and how to set them at higher level.

## Protocol level
IIRC we had a couple of options for incoorperating fees into a mediated transfer:
* Combine transferred amount and fees into a single field in the message. The target would then check if the remaining amount is big enough (how is the amount transfered to the payee?) and otherwise revert the transaction. Idea here is that the mediators don't know about the amount of fees reserved and are incentivized to take fees according to their fee schedule.
* The fees are separated from the transfered amount, every mediator takes some fee. Here the last mediator would take the rest of the fee.
* Specify a fee for the transfer, every mediator gets a fee according to its position in the transfer, e.g. mediator n gets 1 / (2^n) of the total fees. That would incentivize hubs to take light clients that want to pay, but not incentivize hubs to deposit channels to light nodes.

## Fees in general
How should fees work?

* Constant fees
* Relative fees
* Combination fees: Base fee + amount relative to payment
* Imbalance fees

## References:
* Trustlines fee doc: https://docs.google.com/document/d/1WCY66FzI9KlSMLiYnXuCTtKisRVB4o91q_gBHJOcuc8/edit

**Comment by err508** [comment]
Decide on fee representation, i.e. use percent (with float), use basis points, come up with an own convention.

**Comment by loredanacirstea** [comment]
Notes from the 24 August planning meeting regarding this:

## Raiden Client Mediation Fees:
- will be paid in the token that is being transferred through the mediated transfer
- additional `fee` field in the balance proof messages
- the amount represented by the `fee` will also be included in the `locked_amount` of the balance proof, to ensure that the tokens can be recovered through the existing protocol; the smart contracts therefore do not need to change; therefore, the fee will be sent along with the `HTL`
- this `fee` will be the sum of all the fees that the mediated transfer needs to be completed.
- (tbd) each Raiden node will subtract its fee from `fee` and add the new remaining `fee` value to the `locked_amount` of the balance proof, after the balance proof has been updated with the `HTL` values.
- fees are correlated with the channel capacities imbalance; the fee function can be of the form `f(x, p) = a + bx + cx^2` (just a suggestion, might be something different), where:
    - `a` can be a custom constant set by the Raiden node, to account for the user’s preference in fees
    - we can find a function for the fee that increases the fee when the transfer causes an imbalance in the participants capacities and decreases the fee otherwise. A simple example: if P1’s available balance is `10` and P2’s available balance is `100`, if the transfer is of 10 tokens from P1 to P2, then the fee must be bigger than it would be from P2 to P1.
    - `p` is the participant; as mentioned above, each participant in a channel will have a different fee, unless they have the same available balance

## PFS:
- will receive the new capacities + fee schedules (fee formula described for mediated transfers) from the Raiden nodes each `x` minutes (`x` tbd)
- percentage for fees needed for a path - padding area for race condition imbalances; the Raiden node will pay a bit more than the fees calculated for a path, to account for changes in the channel capacities that might happen between the calculation and the transfer.

**Comment by hackaugusto** [comment]
> additional fee field in the balance proof messages

Just to emphasize, this doesn't need to be added in the balance proof *data structure*, used by the smart contracts, but only the *mediated transfer message*, used off-chain.

**Comment by LefterisJP** [comment]
Also, as I added in our notes issue, we discussed it should be named `remaining_fee`, as each hop would subtract what is due to them.

**Comment by palango** [comment]
Some thoughts from my side

## Mediators
Mediators do a service by forwarding payments and want to get some rewards for doing that. I can see two motivations for fees:
- In short term the mediator wants to be payed for the mediation service. This results in fees on the amount of the payment (and not the resulting channel (in)balance). This fee can either be an absolute fee, a relative fee based on the payment amount or some combination like `max(rel_fee, abs_fee)`
- In the long term the mediator wants its channels to stay balanced, so (im)balance fees seem to make sense. However we should make sure that they actually work as we expect (I can remember Georg saying that they delayed imbalancing in his network simulations, but didn't avoid it completely), so we need to look into other solutions as well. I think Tobi is doing research in this direction.
Also we should think about the proper formulation (e.g. is a quadratic function a good fit) and what do we want to happen on the limits (should they be reachable or not). My guess is that this also depends heavily on the use-case for the channel, so we might want to make it configurable.

> padding area for race condition imbalances; the Raiden node will pay a bit more than the fees calculated for a path, to account for changes in the channel capacities that might happen between the calculation and the transfer.

While I don't have a better suggestion, this sounds like a horrible solution. Just imagine you payment provider saying: "The payment should cost 0,50€, but add another 10% just to be sure it works as expected".

**Comment by hackaugusto** [comment]
> Decide on fee representation, i.e. use percent (with float), use basis points, come up with an own convention.

Floating point is not a good representation, it's not supported by the EVM nor it's the representation used by ERC20. At most we should consider fixed points but that too is not well supported by the current version of solidity, so I would just stick to plain integers.

**Comment by hackaugusto** [comment]
> additional fee field in the balance proof messages

pros:
- the initiator knows before starting the transfer how much it will be paid in fees
- the target will receive exactly how much it should receive (or a bit more if the last hop didn't take the remaining fees)

cons:
- this allows the last hop in the transfer to get all the remaining fees. This however is not be a drawback in comparison to the version without the fee field, since in that version the same happens but with the target node (which may be paid more or less)

**Comment by karlb** [comment]
See https://github.com/raiden-network/raiden-services/blob/master/adr/003-mediation-fees.md.
