### ISSUE TITLE
Pathfinding Service specs

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#121]
Related: 
- https://github.com/raiden-network/spec/issues/120 (non core smart contracts)
- https://github.com/raiden-network/spec/issues/10#issuecomment-418090358 (mediation fees)

Notes from the 24 August planning meeting regarding this.

## PFS:
- paid in RDN, from the `UDC`
- will receive the new capacities + fee schedules (fee formula described for mediated transfers) from the Raiden nodes each `x` minutes (`x` tbd)
- percentage for fees needed for a path - padding area for race condition imbalances; the Raiden node will pay a bit more than the fees calculated for a path, to account for changes in the channel capacities that might happen between the calculation and the transfer.
- we can have a `PFSC` that acts as a unidirectional payment channel between the users and PFS, using the user's global deposit from `UDC`
- `PFS` can be paid out with probabilistic payments; the user can sign IOUs and send them to a Matrix room 
- the `PFS` must see what IOUs the users has signed and compare with his available deposit from `UDC`; there might be some double spending happening, but it should be minimal; based on the PFS feedback, this can be later improved.

**Comment by palango** [comment]
Related: https://github.com/raiden-network/raiden/issues/2704
