### ISSUE TITLE
Make sure Raiden messages spec is up to date

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#126]
We made some small changes / additions to the protocol in the last period of time. 
We need to:
- make a list of them in this issue
- document them in the spec (would be nice to also reference the code implementation there)

E.g.: after receiving a `SecretRevealed` blockchain event: the node will unlock the tokens for the pending transfer that has that secret and will send the `Secret` message to his partner, with his updated balance proof.

**Comment by jomuel** [comment]
Last updating issue to date: #252
