### ISSUE TITLE
Similar specifications of "Balance Proof" in message spec and contract spec

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#129]
The [messages specification](https://github.com/raiden-network/spec/blob/cddb561d925264c03fbecb7c9e861249c9a874c1/messaging.rst#balance-proof) and the [smart contracts specification](https://github.com/raiden-network/spec/blob/23a74c986ccab673673610469347a1837f23f062/smart_contracts.rst#balance-proof) both specify what "Balance Proof" is.  The two versions differ.

I'm guessing the two specifications define different structures for different contexts (but I'm not totally sure).  An explicit note would be an improvement.

**Comment by loredanacirstea** [comment]
Exactly, the two specifications target the same concept, with different representations in the client vs. smart contracts. 

Cannot think now of a proper way to name them (feel free to propose). 
We could add:
```
# smart contracts spec
Balance Proof

Is created by the Raiden client from the [Balance Proof](link_messages) data structure, used in the off-chain messages protocol.
```

```
# Raiden client
Balance Proof

Data used to compose the [Balance Proof](link_contracts) needed by the smart contracts to update the payment channel end of the participant that signed the balance proof. 
```

**Comment by pirapira** [comment]
Thanks for the clarification.  I'll file a pull-request with these new sentences.

**Comment by pirapira** [comment]
@loredanacirstea  What about calling them "Offchain Balance Proof" and "Onchain Balance Proof"?

**Comment by loredanacirstea** [comment]
Sounds good!

**Comment by LefterisJP** [comment]
@pirapira As dfiscussed in the office the PFS spec is wrong on that one. It should be the offchain balance proof.

**Comment by pirapira** [comment]
@LefterisJP I created an issue about the PFS spec #130.
