### ISSUE TITLE
Terminology proposals

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#13]
- replace `hashlock` with `secrethash`
- explain `lockhash` better, or give at least an example of what the `lock` is/contains :  https://github.com/raiden-network/raiden/blob/5dc039ccc0c51d02534863ef0bd40dbbf9954627/raiden/transfer/state.py#L671
- SC: `deposit` function, the variable that stores all the deposits is `balance` , event is `ChannelNewBalance` . Is `deposit` a better choice than `balance`? (atm I think so)

**Comment by hackaugusto** [comment]
secrethash

**Comment by LefterisJP** [comment]
Let's just go with `secrethash` for the hash of the lock. I can't count the number of times I have been confused by this term.

**Comment by loredanacirstea** [comment]
Opened https://github.com/raiden-network/spec/issues/56 for the `lockhash`. Rest of the terminology proposals have been implemented.
