### ISSUE TITLE
some fields missing from the Balance Proof example in pathfinding_service.rst

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#130]
[pathfinding_service.rst](https://github.com/raiden-network/spec/blob/74062735d1b42843f89a28c82aa4a37016289d45/pathfinding_service.rst#example) contains an example of a balance proof in a ``api/1/<token_network_address>/<channel_id>/balance`` call.  The example does not look like an onchain Balance Proof or an offchain Balance proof, but @LefterisJP told me that the API should take an offchain Balance Proof.

The example in `pathfinding_service.rst`:
```
    // Request
    curl -X PUT --data '{
        "balance_proof": {
            "nonce": 1234,
            "transferred_amount": 23,
            "locksroot": "<keccak-hash>",
            "channel_id": 123,
            "token_network_address": "0xtoken"],
            "chain_id": 1,
            "additional_hash": "<keccak-hash>",
            "signature": "<signature>"
        },
```

I guess `locked_amount` and `sender` are missing.

**Comment by pirapira** [comment]
When I insert a `print(body)` and run ` ~/src/raiden-pathfinding-service(master) $ pytest pathfinder/tests/test_rest.py::test_put_balance -v -s` I see

```
pathfinder/tests/test_rest.py::test_put_balance
{
"channel_identifier": 123,
"token_network_address": "0x82dd0e0eA3E84D00Cc119c46Ee22060939E5D1FC",
"balance_hash": "0x255ace0592d6d0057743ec81f2494d71fe5466986a2fd6f28c632dc1ef83d48b", "additional_hash": "0x0000000000000000000000000000000000000000000000000000000000000000", 
"nonce": 1,
"chain_id": 1,
"signature": "0xcee72c61fc82cfb1cd42d2205a0982f10c514b48b385f739b524f6072a0edd2b57a9f45320e7265c2b18c1db3fb4181102230feaad52eeb215a54ee232835c301b",
"transferred_amount": 1,
"locked_amount": 0,
"locksroot": "0x0000000000000000000000000000000000000000000000000000000000000000", 
"message_type": "BalanceProof"
}
```
(with newlines added).

* I don't see a `sender` field, so it's not necessary.
* I don't know if the API still works without the `message_type` field.

**Comment by hackaugusto** [comment]
> I guess locked_amount and sender are missing.

The sender field must be computed out of the signature, having it in any of the messages is a security flaw. Perhaps we should remove it from the off chain balance proof to avoid confusion.

**Comment by pirapira** [comment]
@hackaugusto good idea.  I created an issue for that https://github.com/raiden-network/spec/issues/133.
