### ISSUE TITLE
Remove sender field from messages with signatures

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#133]
As @hackaugusto [says](https://github.com/raiden-network/spec/issues/130#issuecomment-439431552), since message senders should be computed from the signature, the sender fields should be removed from messages with signatures.

I've already observed that sender field is not necessary: https://github.com/raiden-network/spec/issues/130#issue-381589508

* [x] remove the sender field from the spec
* [ ] remove the parsing of `sender` field from the implementation, when it deals with signed messages (this can be ticked when a issue is created in the impl repository).

**Comment by hackaugusto** [comment]
As for the parsing, the client and the smart contracts already behave correctly, not sure about the other services. @palango do you know?

**Comment by pirapira** [comment]
I'll have a look into Monitoring Service, and show @palango what I find.

**Comment by palango** [comment]
@pirapira It uses the same foundational code in the raiden-libs, so it should be the same.

**Comment by pirapira** [comment]
I started from the Monitoring Service, and found the `raiden-lib` code that @palango mentioned.  https://github.com/pirapira/raiden-libs/blob/c20a9aa1e84bb4afa36cc5e5e50693ac4215fa84/raiden_libs/messages/balance_proof.py#L145

**Comment by pirapira** [comment]
@loredanacirstea showed me [a class with `sender` field](https://github.com/raiden-network/raiden/blob/fc6028e14c15448c9f3a08b10a5958c0863493d2/raiden/transfer/state.py#L811).  She tells me objects of this class `BalanceProofSignedState` will be sent over the network.  Reopening the issue to clear this out.

**Comment by LefterisJP** [comment]
As I mentioned in comments [1](https://github.com/raiden-network/spec/pull/135#issuecomment-442041772) and [2](https://github.com/raiden-network/spec/pull/135#issuecomment-442042478) in the spec repo:

In the client, `BalanceProofUnsignedState` is not what is sent to or received from the wire. It's just a nice construct we use to keep the balance proof along with its sender inside the state machine and the client in general.

What goes in the wire is the [packed balance proof](https://github.com/raiden-network/raiden/blob/fc6028e14c15448c9f3a08b10a5958c0863493d2/raiden/transfer/balance_proof.py#L15) which does not contain a `sender.

**Comment by pirapira** [comment]
@LefterisJP I had a look too.  Thank you.

@loredanacirstea if you agree, please close this issue.

**Comment by loredanacirstea** [comment]
Yes, I agree.
