### ISSUE TITLE
Add Refund Transfer message in the messages specification

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#173]
Currently [messages.rst](https://github.com/raiden-network/spec/blob/a6b3a451b2e40b91a1b013c4bb53024ff427f949/messaging.rst#messages) does not specify the fields of Refund Transfer messages.  This issue keeps track of adding such specification.

**Comment by karlb** [comment]
https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#refund-transfer looks sufficient to me, now.
