### ISSUE TITLE
Use CI to run Sphinx

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#189]
Currently, the spec repository has no continuous integration.  This issue keeps track of adding it.  At least sphinx-build should run successfully before any PR is merged.

**Comment by karlb** [comment]
This looks like the right way to solve this: https://blog.readthedocs.com/building-docs-for-pull-requests/

I'll write a mail to get it enabled for the spec repo and see if I can turn the integration on.

**Comment by palango** [comment]
Fixed by https://github.com/raiden-network/spec/pull/316 , if the github integration works reliably we can also remove the CircleCI config agin.
