### ISSUE TITLE
Consider including raiden-contracts as a git submodule

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#210]
Currently `spec` repo contains some Solidity files copied from https://github.com/raiden-network/raiden-contracts .  Can&should we use a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) instead of copying contracts over?

Opinions? @karlb

**Comment by hackaugusto** [comment]
Why not just a link? This repo doesn't need the code, does it?

**Comment by LefterisJP** [comment]
> Why not just a link? This repo doesn't need the code, does it?

+1. Submodules can get annoying really fast. There is no need to get that complicated if the actual code is not needed.

**Comment by palango** [comment]
> Why not just a link? This repo doesn't need the code, does it?

The code is used to generate docs from the docstrings. For the discussion for why the code is included see https://github.com/raiden-network/spec/pull/204

**Comment by karlb** [comment]
> Can&should we use a git submodule instead of copying contracts over?

Pro:
- submodules provide a clean and transparent way to include a specific revision of the other repo

Con:
- the whole repo must be included
- many people don't know how submodules work
- even those who know submodules often find them surprising or complicated

**Comment by pirapira** [comment]
The poll is closed.
