### ISSUE TITLE
Should some/all services monitor every TokenNetwork?

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#221]
I saw @LefterisJP and @palango disagree on this point.

@LefterisJP https://github.com/raiden-network/raiden-contracts/issues/734#issuecomment-472445388
> Services won't work by monitoring every single Token Network into existence. That makes no sense.

@palango https://github.com/raiden-network/raiden-contracts/issues/734#issuecomment-472409292
> I always assumed that services should support all token networks.

**Comment by LefterisJP** [comment]
@pirapira After our dfiscussion with Stefan and @palango today I guess it's clear we need each service to monitor a specific set of Token Networks.

**Comment by pirapira** [comment]
Yes, many things will be specific to each situation.
