### ISSUE TITLE
A overflow question about Solidity Settlement Algorithm

### ISSUE THREAD

**Issue by wxdbt** [raiden-network/spec#227]
when P2 has submitted an old balance proof for P1,  P2 may make T1 + L1 smaller than expected, and  RmaxP1 = TLmax2 - TLmax1 + D1 - W1 may overflow , so RmaxP1 may smaller than expected， RmaxP2= TAD-RmaxP1 will bigger. In smart_contracts paper，we only consider the overflow questions when there are last balance proofs. may we should have some additional limit for this ？

**Comment by pirapira** [comment]
`settleChannel()` fails when `TLmax2` is smaller than `TLmax1`.  This happens [here](https://github.com/raiden-network/raiden-contracts/blob/d811ac98b53b0b132b0873712256fe6b8837e82b/raiden_contracts/data/source/raiden/TokenNetwork.sol#L1404) in the code.  So the underflow does not happen.

(In this case, the caller is expected to swap P1 and P2 completely, so the new TLmax1 is the old TLmax2, and the new TLmax2 is the old TLmax1.)

If this answers your question, please close the issue.
