### ISSUE TITLE
Discuss supporting another signature standard for balance proofs

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#23]
Balance proofs and other signed messages for channel life cycle purposes.
Discuss support for EIP712 when finalized, or another standard that makes sure the users can trust the signer.

Users should be able to see what they sign if needed, even though now the signatures are made by the Raiden Network client under the hood.
Users should be protected from replay attacks. This can be enforced by the signed message and not necessarily by the signature standard.
Ideally, users should be sure that what they sign is intended for the use that they assume (Keep an eye on EIP719)

**Comment by LefterisJP** [comment]
> Also, I don't think we should ask for the user attention to sign the SecretReveal and Unlock messages, IMO this will be a bad user experience.

I also agree here. Microraiden's UX (which is what I think you take the example from) is different than Raiden's. 

The whole point of Raiden's UX is that the nodes does everything for the user and as far as he is concerned he just makes fast transfers without knowing how. Introducing any interaction there would break this so I really don't think this is a good idea.

> I need to think about this a little - especially about what user-related risks there are if others implement clients - maybe malicious ones. And if we can/want to enforce some security mechanisms in the smart contracts.

I really think it makes no sense. A malicious client can simply steal all your funds by reading your private key. There is nothing we can do if the user's client is compromised and we should not complicate the protocol any further trying to help situations that just can't be helped.

**Comment by pirapira** [comment]
Since we're live on the main net, it does not make much sense to change the signature format at the moment.
