### ISSUE TITLE
Specs for the MS rewards system

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#25]
Write specs on how Monitoring Service rewards will be paid. 

MS = Monitoring Service
MSC = Monitoring Service Contract

**Requirements**
- core protocol is unaffected
- reduced number of channels that a user (Raiden node / Raiden Light Client) needs to open when onboarding
- reduced gas cost
- reduced development complexity

**Note**
- a MS needs to deposit tokens in a MSC
- MSC needs to keep a registry of approved MS

Latest proposal: https://github.com/raiden-network/spec/issues/25#issuecomment-375467874

**Comment by loredanacirstea** [comment]
MS = Monitoring Service
MSC = Monitoring Service Contract
BP = Balance Proof
TNC = TokenNetwork type of contract

My take:
- solution should permit payments in both the TokenNetwork token & RDN.
- MS must call `updateTransferDelegate` and `unlock` (he needs the `hashlock`, `merkle_proof` & `secret` that must correspond to his BP)
- MS must be rewarded (the amount can be 0)


End to end:

- Participant needs to provide 2 amounts - for channel token & RDN (can be done under the hood for 1 of them)

1) Pay MS with `TokenNetwork` token
1. MS ensures that the user would have enough settlement tokens to pay the reward
2. MS calls `delegateUpdateTransfer` with `non_closing_signature` on (`reward_amount`, BP data)
3. `TokenNetwork` stores the the `MS_address` & `reward_amount`
4. MS calls `unlock` if neccessary
5. possibly more MS can do 2, 3, 4 and we overwrite the `MS_address` & `reward_amount` (no need to pay for old BPs) + remove `reward_amount_rdn`
6. when `settleChannel` is called, MS is also paid by transferring the `reward_amount` from the settlement tokens.

GAS COST first call: 40k storage + 1 token transfer

2) Pay MS with RDN token
1. MS ensures that the Participant has a big enough RDN deposit in the MS contract
2. MS calls `delegateUpdateTransferRDN` with `non_closing_signature` on (`reward_amount_rdn`, BP data),
3. `TokenNetwork` stores the the `MS_address` & `reward_amount_rdn`
4. MS calls `unlock` if neccessary
5. possibly more MS can do the same thing (2, 3, 4) and we:
  - decrease Participant's owed tokens
  - overwrite the `MS_address` & `reward_amount_rdn` (no need to pay for old BPs)
  - remove `reward_amount` 
6. when `settleChannel` is called, MS is also paid by transferring the `reward_amount_rdn` from the MSC to the MS account.

GAS COST first call: 40k storage + 1 token transfer + external function call


**So, we would need to:**
- store the monitoring contract address globally in the TokenNetwork contract


**Alternatives:**

- storing `MS_address` & `reward_amount`/`reward_amount_rdn` can happen in MSC

We have been thinking about MS getting paid through Raiden Network, but this has the double deposits issue. So, I have also been thinking about using uRaiden for paying with RDN.
- big PRO - using off-chain payments with small rewards. The issue is what happens after settling - you need an actual signature for off-chain.
- an alternative would be to just do an owed tokens increase on chain (5k gas) from the TokenNetwork contract - which would be a trusted contract, so you could do this without a signature (needs uRaiden contract change)
- might be more gas efficient.



**Issues:**
- how do we ensure transfers are `unlocked`? This means additional transactions that MS might not want to do. How do you punish them for not unlocking?

**Comment by loredanacirstea** [comment]
```
MonitoringService Contract
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

.. Note::
    The MS will only be paid if he is the MS that provides the most up-to-date balance proof when calling ``updateTransferDelegate``. 

    The MS is paid only when `settleChannel` is called, by transferring the `rewarded_tokens` from the MSC to the MS account.


Attributes:

- data structure that stores deposited amounts per participant


**Deposit tokens**

A participant needs to deposit tokens in the contract in order to pay rewards.

::

    function deposit(address participant, uint256 total_token_amount) public

::


- ``participant``: address of the channel participant that uses the MS.
- ``total_token_amount``: total amount of tokens that will be deposited to the MS contract for paying rewards.

.. Note::
    This function is idempotent. The actual amount of tokens transferred by `deposit` is ``total_token_amount`` - already deposited tokens.



**Withdraw tokens**

A participant needs to be able to withdraw tokens. He must not be able to withdraw tokens that are promised in an ongoing channel closing.

**updateTransfer**

This function is called by any MS that wants to update the balance of a participant after a channel has been closed.

::

    function updateTransfer(
        uint256 channel_identifier,
        uint256 chain_id,
        uint64 nonce,
        uint256 transferred_amount,
        bytes32 locksroot,
        bytes32 additional_hash,
        uint256 rewarded_tokens,
        bytes closing_signature,
        bytes non_closing_signature)
        public

::

Needs to call ``TokenNetwork.updateTransferDelegate``.
Needs to store the MS Ethereum address (``msg.sender``) & ``rewarded_tokens``. It needs to overwrite these values whenever ``updateTransferDelegate`` returns ``True``.

- ``non_closing_signature``: Signature of the non-closing participant on ``(channel_identifier, chain_id, token_network_address, nonce, transferred_amount, locksroot, additional_hash, rewarded_tokens)``


**unlock**

This function is used by any MS that wants to update the ``transferred_amount`` of a participant by unlocking locked transfers.

This is called after a channel has been closed and after ``updateTransfer`` has been called.
This must be called if there are unlocked transfers.

.. Note::
    If updateTransfer has been called again on the ``TokenNetwork`` type contract, all the unlocked locks need to be unlocked again.

```

**Comment by loredanacirstea** [comment]
This issue is related: https://github.com/raiden-network/spec/issues/31

**Comment by pcppcp** [comment]
I'd add

* reward will be paid to one `Updater` only (to prevent someone from submitting multiple BPs)
* there is no requirement for BP to be up-to-date, we can't check for that anyway. The only metric for SC and accepting delegated `updateTransfer` should be a nonce (must always increase) AND a signature of both parties

Open questions
* what if no `updateTransfer` is done? Then the reward should either be transferred back to the Raiden node address, or it should be possible to reuse it

**Comment by czepluch** [comment]
> what if no updateTransfer is done? Then the reward should either be transferred back to the Raiden node address, or it should be possible to reuse it

The way I see it, it makes sense to deposit more tokens than just the tokens needed for a single reward. This is to save gas by only doing one tx instead of doing a tx every time one deposits. So the MS should only be allowed to "deduct" some portion of the deposited amount.

**Comment by loredanacirstea** [comment]
# Summary of proposed changes

(WIP)

## TokenNetwork

```
    bytes32 balance_proof_hash = keccak256(
        transferred_amount,
        locksroot,
        channel_identifier,
        address(this),
        chain_id,
        additional_hash
    );
```

```
    function updateTransfer(
        bytes32 balance_proof_hash,
        uint64 nonce,
        bytes closing_signature,
        bytes non_closing_signature)
        external

    function updateTransferDelegate(
        bytes32 balance_proof_hash,
        uint64 nonce,
        bytes closing_signature,
        bytes non_closing_signature)
        external

    function recoverAddressFromSignature(
        bytes32 balance_proof_hash,
        uint64 nonce,
        bytes signature)
    {
        bytes32 message_hash = keccak256(balance_proof_hash, nonce);
        var (r, s, v) = signatureSplit(signature);
        return ecrecover(message_hash, v, r, s);
    }

```

## Logic


### Off-chain

```
balance_proof_data = (channel_identifier, nonce, transferred_amount, locksroot, channel_identifier, token_network_address, chain_id, additional_hash)
```

```js
A -> B: balance_proof_data, + A_signature(balance_proof_hash, nonce) 

// Note: ! B at this point must verify balance_proof_hash by using ecrecover on the reproduced (balance_proof_hash, nonce) 

B -> MS1: A_signature(balance_proof_hash, nonce), B_signature(balance_proof_hash, nonce), balance_proof_hash, nonce

// B goes offline

MS1 -> TokenNetwork.updateTransferDelegate: balance_proof_hash, nonce , A_signature(balance_proof_hash, nonce), B_signature(balance_proof_hash, nonce)

// TokenNetwork stores balance_proof_hash , nonce

MS2 -> TokenNetwork.updateTransferDelegate: balance_proof_hash2, nonce​​​​​​​2, A_signature(balance_proof_hash2, nonce2), B_signature(balance_proof_hash2, nonce2) -> compare nonces and take the highest

A / B -> TokenNetwork.settleChannel: balance_proof_data  -> compare with stored balance_proof_hash, nonce
```

**Comment by hackaugusto** [comment]
We need to change the `updateTransfer` signature and add a few missing methods. Bellow is the on-chain flow to shown what I mean. 

If the counter party is online:

1. TokenNetwork.openChannel
2. TokenNetwork.closeChannel
4. **TokenNetwork.updateTransfer** (The balance proof fields must be provided as function arguments. I think this should also be renamed, perhaps setCloserBalanceProof. Callable once by the counter party)
5. TokeNetwork.settleChannel

If a MS is used:

1. TokenNetwork.openChannel
2. TokenNetwork.closeChannel
3. TokenNetwork.updateTransferDelegate (I think this should be renamed, maybe updateCloserBalanceProofHash, callable by anyone, change the hash if a higher nonce is provided)
4. **TokenNetwork.setCloserBalanceProofForHash** (missing, callable by anyone, including the closer, receives the balance proof data, computes the hash, validates against the hash provided by the previous step. I think this should only be allowed after the settlement period, not sure if this can be called multiple times since we expect the balance proof to be updated in the settlement window, allowing it to be called only once will probably make things simpler)
5. TokeNetwork.settleChannel (I think we should add a facade for setCloserBalanceProofForHash and settleChannel as an optimization for the closing party sake, e.g. setCloserBalanceProofForHashAndSettle)

**Comment by LefterisJP** [comment]
Yes with the new approach it would make little difference to the contract who it is that executes the update (which I also view as elegant and nice).

So just keeping a single `updateTransfer()` without any suffix sounds good.

**Comment by loredanacirstea** [comment]
# Latest proposal:


## TokenNetwork contract

```
    bytes32 balance_hash = keccak256(
        transferred_amount,
        locksroot,
        additional_hash
    );
```

```
    function updateTransfer(
        bytes32 balance_hash,
        uint256 channel_identifier,
        uint64 nonce,
        bytes closing_signature,
        bytes non_closing_signature)
        external

    function recoverAddressFromSignature(
        bytes32 balance_hash,
        uint256 channel_identifier,
        uint64 nonce,
        bytes signature)
    {
        bytes32 message_hash = keccak256(balance_hash, address(this), chain_id, channel_identifier,  nonce);
        var (r, s, v) = signatureSplit(signature);
        return ecrecover(message_hash, v, r, s);
    }

```

## Logic


- MS makes a big deposit in the MS Contract
- if all MS fail to call `updateTransfer` and Raiden node loses tokens, they are punished by forfeiting part of this deposit (burned, donated etc., but it should NOT go to the node that called MS)

```
balance_data = (transferred_amount, locksroot, additional_hash)
balance_proof_hash = keccak256(balance_hash, token_network_address, chain_id, channel_identifier, nonce)

```

```js
A -> B: balance_data, token_network_address, chain_id, channel_identifier, nonce  + A_signature(balance_proof_hash) 

// Note: ! B at this point must verify balance_hash by using ecrecover on A_signature(balance_proof_hash)

B -> MS_Matrix_channel: A_signature(balance_proof_hash), B_signature(balance_proof_hash), balance_hash, token_network_address, chain_id, channel_identifier, nonce

// reward_amount must be signed and incorporated

MS_Matrix_channel -> MS1: picks up balance proof
MS_Matrix_channel -> MS2: picks up balance proof

MS1 -> B: signed off-chain receipt
MS2 -> B: signed off-chain receipt

// TODO: define receipt

B -> MS1: small off-chain payment = reward
B -> MS2: small off-chain payment = reward

// Use uRaiden for these off-chain payments. Every MS that sends a receipt receives an off-chain payment

// B goes offline

MS1 -> TokenNetwork.updateTransfer: balance_hash, channel_identifier, nonce , A_signature(balance_proof_hash), B_signature(balance_proof_hash)

// TokenNetwork stores balance_hash , nonce in channels(channel_identifier)

MS2 -> TokenNetwork.updateTransfer: balance_hash2, channel_identifier, nonce2 , A_signature(balance_proof_hash2), B_signature(balance_proof_hash2) -> compare nonces and takes the highest

A / B -> TokenNetwork.settleChannel: balance_proof_data  -> compare with stored balance_hash
```

**Comment by loredanacirstea** [comment]
To be determined:

- off-chain `receipt` format
- MS onboarding / token bonding + punishment protocol (how do you prove the `MS`s did not do it’s job - receipt + payment proof). Punishment is hard, we really need to think about incentives here.

Note:
- MS services should ideally not know about one another, to force them all to call `updateTransfer`.

**Comment by loredanacirstea** [comment]
CC: @hackaugusto ,
Additional issue to be aware of (raised by @konradkonrad ):
We now offer balance proof privacy by using a BP hash. This means some issues at `settleChannel` time in case the non-closing participant loses the state (`balance_data`).
Specifically, this case would pose problems:
- non-closing participant has a lot of tokens to receive
- closing participant has few/none tokens to receive
- non-closing participant has lost it's state (computer crash)

Now, I think this specific issue of losing your state because of a computer crash / state data loss is on the client's back. 
He MUST backup his data and store it somewhere from time to time. 
However, we need to make sure the Raiden client does not have crashes.

Alternative solution:
- PFS might work in the same bundle with the MS - you might retrieve your `balance_data` from there.

**Comment by nkbai** [comment]
If there are a lot of MS contention call update transfer, it will cause a lot of failure, only one of them is  success, this will waste a lot of gas. This would actually cause MS to have no incentive to do his job.
for example .
A close channel at block 1000, then  ALL the MS will try to call updateTransfer at block 1001，if only one can be success, others will not call updateTransfer nexttime.

**Comment by LefterisJP** [comment]
@nkbai That is correct. To address this problem we want the user to randomly pick an order of MS each time and give them one by one a chance to close as time passes.

For possible implementations read [this comment](https://github.com/raiden-network/spec/issues/46#issuecomment-3777769160

**Comment by LefterisJP** [comment]
@nkbai Because you can never trust a single MS only. The danger of collaboration with the counterparty is just too great.

**Comment by nkbai** [comment]
If the tokens is too much, the raiden node should keep online.  Not all operations need to be decentrailized.  if MS forget ( maybe on purpose), find a way to punish him . for example, there are Third party rating agencies.

**Comment by nkbai** [comment]
or MS store a lot of tokens on a contract, once a raiden node can prove MS's derelicton of duty, this node can get 3 times of lost tokens etc.
