### ISSUE TITLE
make html emits a warning

### ISSUE THREAD

**Issue by pirapira** [raiden-network/spec#259]
In a fresh venv (python 3.7), after a `pip install -r requirements.txt` and `make html` I see a warning

```
Warning, treated as error:
/home/yoichi/src/spec/smart_contracts.rst:521:term not in glossary: balance proof update
make: *** [Makefile:65: html] Error 2
```

This issue keeps track of fixing this warning.

**Comment by LefterisJP** [comment]
That's because we have warnings treated as errors locally but in read the docs this is not the case I think

**Comment by pirapira** [comment]
@LefterisJP I still want to enable `warning-as-error` in the CI https://github.com/raiden-network/spec/issues/260

**Comment by pirapira** [comment]
Here we concentrate on fixing the warning.
