### ISSUE TITLE
Assess support for decentralized pathfinding

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#29]
Assess support for decentralized pathfinding, because the pathfinding algorithm must enforce structure in the network.

Decentralized pathfinding is work in progress. The current pathfinding approach that is being worked on is a federation of pathfinding helpers, therefore this issue is not urgent.

**Comment by karlb** [comment]
Pathfinding is delegated to the PFS and not the concern of a Raiden node, anymore.
