### ISSUE TITLE
Add a check for correctness of pull requests

### ISSUE THREAD

**Issue by jomuel** [raiden-network/spec#306]
Currently pull requests to this repo are not built before merging and thus not checked for correctness at all. At least two prs have been merged in the past that introduced trivial errors like wrong indentation, so that the post-merge build on readthedocs.io failed and had to be debugged. It would be more efficient to catch such errors in advance.

**Comment by palango** [comment]
Should be fixed with https://github.com/raiden-network/spec/pull/316

**Comment by karlb** [comment]
We finally got https://blog.readthedocs.com/building-docs-for-pull-requests/ enabled for this repo:
> I have enabled the feature for your project.
> Make sure  that the GitHub webhook has the  pull_request event enabled. Let us know if you have any feedback from the feature.

I'll give it a try when I next work on the spec.
