### ISSUE TITLE
[SP 3] Changes to mediation fees chapter

### ISSUE THREAD

**Issue by jomuel** [raiden-network/spec#307]
To do for the mediation fee chapter until the Alderaan release:

- [ ] Read the mediation fee spec
- [ ] Clarify unclear parts
- [ ] Ask Jochen about his proposals:
    - [ ]  give it a better overall structure
    - [ ] clarify how the approximation (_b' ≈ b_) is computed

**Comment by Dominik1999** [comment]
closing this for now. We cannot specify that further
