### ISSUE TITLE
[SP 2] Remove `LockedTransfer.fee` from spec

### ISSUE THREAD

**Issue by palango** [raiden-network/spec#321]
Adapt the spec after https://github.com/raiden-network/raiden/pull/5077

- [ ] Update message field tables
- [ ] Update example messages
    - There might be a script for that. @kelsos can you clarify?

**Comment by kelsos** [comment]
@palango When I was doing the LockedTransfer documentation update and for the Light Client messaging packing/signing implementation I did this script https://github.com/kelsos/raiden-protocol-messages/blob/master/messages/messages.py to help me.
