### ISSUE TITLE
Updating the Raiden Spec with RFCs of the Raiden Light Client implementation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/spec#334]
### Problem
Within the Raiden Light Client implementation, we have got a few Raiden protocol additions which we would like to add the Raiden protocol specification (eg. WebRTC, capabilities, etc.).

### Proposed Solution
We would create a PR to the Raiden specification describing the protocol extensions.

## Question
@Dominik1999 What do you think?

CC @andrevmatos @hackaugusto

**Comment by palango** [comment]
Tracked in https://github.com/raiden-network/team/issues/882
