### ISSUE TITLE
Add a batch version of unlock

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/spec#35]

**Comment by loredanacirstea** [comment]
Documenting what Augusto said: maybe some gas cost can be saved by calculating the locksroot on chain for all these locks, as opposed to calling `computeMerkleRoot` for each lock.

**Comment by loredanacirstea** [comment]
After a talk with @hackaugusto  &  @konradkonrad :

(see also https://github.com/raiden-network/spec/issues/31#issuecomment-375474972)

Code below is provided just as a draft - not tested, probably not compilable.

```
// 96 bytes
lockdata = locked_amount || expiration_block || hashlock
```

```
merkle_tree_component_hash = \x00 || lockhash // 33 bytes
merkle_tree_component_data = \x01 || lockdata  // 97 bytes
```

`merkle_tree` = concatenation of all unlocked transfers; these can have revealed or unrevealed secrets
- if `secret` is revealed: `merkle_tree_component_data` ->  MUST check `expiration_block` for each from `SecretRegistry. lockhash_to_block(lockhash)`
- if `secret` is not revealed/expired etc. : `merkle_tree_component_hash` -> to be able to calculate `computed_locksroot`

```
function unlock(
        uint256 channel_identifier,
        address partner,
        bytes merkle_tree)
        public
    {
     bytes32 computed_locksroot = computeMerkleRoot(merkle_tree);
     require(partner_state.locksroot == computed_locksroot);
    }
```

**Comment by hackaugusto** [comment]
@loredanacirstea your previous comment is too loosely defined. It's hard to understand if/how will it work. Assuming:

- A channel implementation that:
  - Requires the lock expiration to be smaller than the settlement period
  - Uses a balance proof **with** the `locked_amount`
- An unlock function that:
  - Requires the whole merkle tree as input (a list of all the leaves in the tree)
  - May only be called after the settlement window

Then I think the proposal is okay, were the transfers would be:

```
// pseudo code
unlocked_amount = sumUnlockedLocks(); 
token.transfer(bp_signer, balance_proof.locked_amount - unlocked_amount);
token.transfer(counterparty, unlocked_amount);
```

But I'm not sure if the requirements, and specially the optimization for the unlocked locks are the best options choices

**Comment by hackaugusto** [comment]
I thought a bit more about the case were the secret is not revealed, and *we need the hashlock* to know if that is true or not, providing only the lockhash is **not** sufficient.

**Comment by loredanacirstea** [comment]
Then we only have `merkle_tree_component_data` of 96 bytes concatenated. Simpler to handle.

**Comment by hackaugusto** [comment]
As documentation from our chat:
```
- Each participant controls its end of the netting channel
- At any point in time, there may be multiple hash-time-locks pending, meaning a merkletree is compose of `0 to Lt` locks
- These locks may or may not have the secret revealed, in no specific order
- Once the channel is *closed on-chain*, the raiden node must stop doing *off-chain transactions*, meaning that the merkle tree is composed of `0 to Lt` locks, of which `0 to Lu` are unlocked, and `0 to Ll` are still locked. The interesting part here, is that the number of locks unlocked may change until the settlement period is over.
- After the settlement period, all locks will either be unlocked or not, so the numbers `Ll` and `Lu` don't change anymore (assuming that we *required as part of the protocol* that all locks must have an expiration lower than the settlement period)
- At this point, the `locked_amount` or `sum(l.amount for l in Lt)` is held in the smart contract, and `deposit - locked_amount - transferred_amount + received_amount` may be transferred to each participant
- From the `locked_amount`, `sum(l.amount for l in Lu)` must go to the counterparty and `sum(l.amount for l in Ll)` must go to the owner of the owner of the channel direction
```

**Comment by LefterisJP** [comment]
> Once the channel is closed on-chain, the raiden node must stop doing off-chain transactions, meaning that the merkle tree is composed of 0 to Lt locks, of which 0 to Lu are unlocked, and 0 to Ll are still locked. The interesting part here, is that the number of locks unlocked may change until the settlement period is over.

Question:

With this scheme why would we have up to `Lu` locks unlocked before the end of settlement? So we allow anyone to unlock a lock normally before the settlement period but also now after the settlement period?

What would the incentive be to unlock a lock before settlement? Just getting your money out faster (at `settle()`) as opposed to the batch unlock after settle?

**Comment by hackaugusto** [comment]
> And this happens when? Still at settle()?

at `unlock`

**Comment by LefterisJP** [comment]
So then `settle()` would dispense the `transferred_amount` to the participants and `unlock` the locked amount?

**Comment by hackaugusto** [comment]
> So then settle() would dispense the transferred_amount to the participants and unlock the locked amount?

That's how I'm thinking about it, yes.

We may have a bit of margin to optimization here, using a single function to do both and reducing the number of transactions, but I'm still trying to figure out *exactly* how the unlock will work.

**Comment by loredanacirstea** [comment]
> So then settle() would dispense the transferred_amount to the participants and unlock the locked amount?

Yes, exactly. Let's keep optimizations after we actually have the functions. 
But yes, I was also thinking about optimizing this in a single function when thinking about withdrawals.

**Comment by loredanacirstea** [comment]
@hackaugusto , check an update at https://github.com/raiden-network/spec/issues/35#issuecomment-375480433.  Konrad's idea to add the hash optimization was due to knowing the `locked_amount` from `updateTransfer` (as we were discussing).

**Comment by hackaugusto** [comment]
> check an update at #35 (comment). Konrad's idea to add the hash optimization was due to knowing the locked_amount from updateTransfer (as we were discussing).

> don't forget about locked_amount - that would be sent as balance proof data in updateTransfer - this is the total amount of tokens that the participant has in locked transfers that can be unlocked; this is why we could optimize with hashes instead of full data, because we can check locked_amount == computed_locked_amount_from_merkle_tree
> must check if there is a possibility of locked funds inside the TokenNetwork contract

Only the lockhash **is not sufficient** to know if the secret was revealed or not, *the secret_hash and expiration must be provided*. Example:

- A sends a MediatedTransfer to C through B (A-B-C)
- A **reveals** the secret to C
- C reveals the secret to B *and* B sends a Balance Proof to C, so B has paid C
- A **does not** send a BalanceProof to B
- A: closes channel A->B
- B: calls updateTransfer

Now, as we have discussed, anyone **must** be allowed to call unlock for either participant, otherwise we could have funds locked in the channel. But here we have a race condition, it's on A's interest to call unlock only with the lockhash, the smart contract would then **assume** the lock was not unlocked, *it cannot verify that is the case without known the secret_hash*, so A will effectively steal B's funds for the mediated transfer above. 

You're forgetting the tokens locked by the locks in the merkletree don't go to only one of the parties, which party receives the tokens depends on the secret registration, and if the lock was unlocked or not must be checked.

**Comment by hackaugusto** [comment]
Here is a sketch for `settle`, based on the current implementation. It withdraws the difference from transferred amount, keeps the locked amount locked, and allows the batch unlock to be executed after to withdraw the locked amount:

```solidity
function settleChannel(
        uint256 channel_identifier,
        address closer_address,
        address counter_address 
)
    isClosed(channel_identifier)
    timeoutOver(channel_identifier)
    public
{
    Channel storage channel = channels[channel_identifier];

    Participant storage closer = channel.participants[closer_address];
    Participant storage counter = channel.participants[counter_address];

    require(participant1_state.initialized);
    require(participant2_state.initialized);

    closer_deposit = closer.monotonic_deposit - closer.monotonic_withdraw;
    counter_deposit = counter.monotonic_deposit - counter.monotonic_withdraw;
    channel_deposit = closer_base_deposit + counter_base_deposit;

    closer_amount = closer_deposit + closer.transferred_amount - counter.transferred_amount;

    // Normalized closer_amount for cases were a balance proof is not provided:
    // - Without the counter balance proof closer_amount will be larger than
    //   channel_deposit
    // - Without the closer balance proof closer_amount will be smaller than
    //   zero
    closer_amount = min(closer_amount, channel_deposit);
    closer_amount = max(closer_amount, 0);

    counter_amount = channel_deposit - closer_amount;

    // A node may have an off-chain capacity larger than its on-chain deposit,
    // depending on the direction of the off-chain transfers. As a consequence, it
    // is possible for a node to have a locked_amount greater than its total
    // deposit.
    closer_locked_amount = closer_bp.locked_amount;
    if (closer_locked_amount > closer_amount) {
        closer_locked_amount -= closer_amount;
        closer_amount = 0;
        counter_amount -= closer_locked_amount;

        // Handle bad nodes, that allow overcommitment of the on-chain deposit
        counter_amount = max(counter_amount, 0);
    } else {
        closer_amount -= closer_locked_amount;
    }

    counter_locked_amount = counter_bp.locked_amount;
    if (counter_locked_amount > counter_amount) {
        counter_locked_amount -= counter_amount;
        counter_amount = 0;
        closer_amount -= counter_locked_amount;

        // Handle bad nodes, that allow overcommitment of the on-chain deposit
        closer_amount = max(closer_amount, 0);
    } else {
        counter_amount -= counter_locked_amount;
    }

    require(token.transfer(participant1, participant1_amount));
    require(token.transfer(participant2, participant2_amount));
}
```

It works, but I really dislike the fix for the locked amount. A way to remove the locked amount fix, is to only allow settle after batch unlock for both participants. The lifetime would be like this:

- channelOpen
- channelWithdraw
  - can be called if the channel is not closed
  - requires the withdraw message and the two signatures
  - callable by anyone
  - can be called multiple times
- channelCloseBalanceProofHash
  - requires the signed counter party balance proof hash
  - can be called if the channel is not closed
  - callable only by a channel participant (may have a delegate version)
  - can be called only once
- channelUpdateBalanceProofHash
  - requires the closer balance proof hash and the two signatures
  - can be called after close and before the settlement window expires
  - callable by anyone
  - can be called multiple times
- channelParticipantBatchUnlock
  - requires the balance proof data
  - requires all the locks that compose the merkle tree as input
  - can be called only after the settlement window
  - callable by anyone
  - can be called once per participant 
- channelSettle
  - can be called only after `channelParticipantBatchUnlock` for both participants
  - callable by anyone
  - can be called once

Allowing settle after unlock removes the need for the fix, since the unlocked_amount would be known, the downside is that a node that wants to withdraw it's tokens needs to call `channelParticipantBatchUnlock` for the counter party (if the counterparty has not done it yet).

**Comment by loredanacirstea** [comment]
You are right here https://github.com/raiden-network/spec/issues/35#issuecomment-375913665 - if we maintain `unlock` as being callable by anyone. The proposed hash optimization is fine only for `unlock` being called by the token receiver. 

Still, providing all merkle tree data ensures tokens are not lost. 
The disadvantage would be gas cost limiting the number of locks in the merkle tree - so I need to calculate some clear numbers here. Until then, I'll stick with your proposal.

**Comment by nkbai** [comment]
Do I need at least four transactions to close a opened channel and get my tokens back?  @hackaugusto

**Comment by LefterisJP** [comment]
@nkai no. That would be **at most** four and not all from you.

1 You call `close()`
2. Your counterparty or its monitor calls `updateTransfer()`
3. Anybody can call settle()
4. Anybody can call unlock (iff there are any locks. If not then there is no reason to call this.)

**Comment by nkbai** [comment]
@LefterisJP  according to @hackaugusto 's proposal. I need  at least four transactions. maybe some of them are called by my delegator.
>
> Here is a sketch for settle, based on the current implementation. It withdraws the difference from > transferred amount, keeps the locked amount in the smart contract, to withdraw the locks it 
> requries a subsequent call to the batch unlock function:

>function settleChannel(
        uint256 channel_identifier,
        address closer_address,
....
    channelOpen
    channelDeposit
        can be called if the channel is not closed
        callable by anyone
        can be called multiple times
    channelWithdraw
        can be called if the channel is not closed
        requires the withdraw message and the two signatures
        callable by anyone
        can be called multiple times (this means we need to share the nonce)
    channelCloseBalanceProofHash
        requires the signed counter party balance proof hash
        can be called if the channel is not closed
        callable only by a channel participant (may have a delegate version)
        can be called only once
    channelUpdateBalanceProofHash
        requires the closer balance proof hash and the two signatures
        can be called after close and before the settlement window expires
        callable by anyone
        can be called multiple times
    channelParticipantBatchUnlock
        requires the balance proof data
        requires all the locks that compose the merkle tree as input
        can be called only after the settlement window
        callable by anyone
        can be called once per participant
    channelSettle
        can be called only after channelParticipantBatchUnlock for both participants
        callable by anyone
        can be called once

**Comment by loredanacirstea** [comment]
@nkbai , we are also planning a cooperative close - you will do only 1 transaction instead of `channelClose`, `updateTransfer`, `channelSettle`.
