### ISSUE TITLE
message RemoveExpiredLock seems useless

### ISSUE THREAD

**Issue by nkbai** [raiden-network/spec#48]
why not let node delete expired lock himself?
a lier node will ignore this message .

**Comment by andrevmatos** [comment]
@nkbai the root of the merkle tree needs to be signed to be useful. This message isn't only a command to remove the lock, but also the signed root of the new tree.

**Comment by nkbai** [comment]
for Channel A-B ,  when A detects a expired hashlock ,A removes it from its own merkle tree.
when B detects a expired hashlock ,B removes it from its own merkle tree. the all listen new block event from ethereum.  why does they need to tell each other that a invalid hashlock is removed?

**Comment by nkbai** [comment]
sorry ,i know what you mean. new locksroot is not signed.
