### ISSUE TITLE
how to deal with refund?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/spec#53]
there is no message about refund in the new specification.
can we make sure there is no need of refund?

**Comment by karlb** [comment]
There is an entry for RefundTransfer in the current spec: https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#refund-transfer.

If a payment is stuck in a dead end, you either need to fail the whole payment or do a refund transfer. If you are ok with letting the payment fail in such cases, you don't need to implement refund transfers.
