### ISSUE TITLE
Allowing multiple channels for the same participants?

### ISSUE THREAD

**Issue by palango** [raiden-network/spec#55]
Right now we allow multiple channels to be opened between the same two Raiden nodes. Supporting this in the PFS requires to change the description of a route from a list of adresses to a list of channels The biggest implication is probably that Raiden clients need to follow all created channels in order to map channel Ids to the participants addresses.

In a discussion here in Berlin we came to the conclusion that this shouldn't be a problem per se, but the question is if we see use-cases for multiple channels. Konrad sees a possible use case in being able to open a second channel as soon as the first channel is in closing state.

Any opinions on that?

**Comment by palango** [comment]
In a discussion we concluded to disallow multiple channels for now and discuss (dis)advantages of this at a later point in time.

### Summary

#### Pro multiple channels
- Allowing creating replacement channels for channels that are either closing or locked in a mediating stage
- Disallowance checks cost gas

#### Contra
- Will require changes in the Raiden API and the PFS

**Comment by loredanacirstea** [comment]
@LefterisJP , please confirm:
We have decided to not allow multiple channels between two participants.

**Comment by LefterisJP** [comment]
@loredanacirstea confirmed

**Comment by loredanacirstea** [comment]
Done in https://github.com/raiden-network/spec/pull/78. Also implemented in https://github.com/raiden-network/raiden-contracts/pull/58
