### ISSUE TITLE
Use bytes instead of bytes32 for the secret in the registerSecret function

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#60]
Asses if the `SecretRegistry.registerSecret` function should use `bytes` instead of `bytes32`, to cover all sizes in case we need to change the way the secret is created.

https://github.com/raiden-network/raiden-contracts/blob/81698bb48c94d0a1be556d8b062d316f1e0fc083/raiden_contracts/contracts/SecretRegistry.sol#L20

The `secret` used now in `raiden` repo has a fixes size of 32 bytes
https://github.com/raiden-network/raiden/blob/ba81dd8ba323958e9718a53766457835f11dcd36/raiden/utils/__init__.py#L34

Notes:

- there is no mention in the spec about the size of the `secret`, so one would assume it can be of any size -> either fix the `spec` or do the above change
- difference in gas costs for both solutions must be calculated

**Comment by hackaugusto** [comment]
I'm good with `bytes32`, variable length will just increase the client complexity.

The size of the secret should depend on the properties of the hash function, as long as the input is large enough for it to be secure, we should be good.

**Comment by LefterisJP** [comment]
I think `bytes32` should be sufficient size for a secret to be secure under all hash functions that we know of.

So fix the spec.

**Comment by LefterisJP** [comment]
Since I am assigned I can do it myself.
