### ISSUE TITLE
TokenNetwork ChannelSettled event - add the transferred amounts as arguments? 

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#70]
tl;dr I want to add the transferred amounts in the `ChannelSettled` event.

Now:

```
event ChannelSettled(uint256 channel_identifier);
```

Should we have:

```
event ChannelSettled(uint256 channel_identifier, uint256 participant1_amount, uint256 participant2_amount);
```

PROs for having the values in the event:
- easier to track the outcome -> have better analytics to test the system
- in case something goes wrong with the token transfers, it would be easier to see if the calculations were wrong or the problem lies somewhere else

CONs:
- privacy - but this is not an issue, because the amounts are visible in the blockchain anyway.

**Comment by LefterisJP** [comment]
@loredanacirstea I think this is a good idea.
