### ISSUE TITLE
Update TokenNetwork.cooperativeSettle signature format

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#71]

**Comment by loredanacirstea** [comment]
@LefterisJP , @hackaugusto , we can discuss the signature format here rather than the PR:

My proposed signature format in https://github.com/raiden-network/raiden-contracts/pull/50 is:

```
function recoverAddressFromCooperativeSettleSignature(
        uint256 channel_identifier,
        address participant1,
        uint256 participant1_balance,
        address participant2,
        uint256 participant2_balance,
        bytes signature
    )
        view
        internal
        returns (address signature_address)
    {
        bytes32 message_hash = keccak256(
            participant1,
            participant1_balance,
            participant2,
            participant2_balance,
            channel_identifier,
            address(this),
            chain_id
        );

        signature_address = ECVerify.ecverify(message_hash, signature);
    }
```

Reason for including the addresses is: you need to choose an order first and then send it to the other participant to sign. This is were I see issues, because you have to pay extra care that the node receiving this message to sign knows how to interpret the balances correctly. I think this format brings more clarity in knowing whose is the balance value.

**Comment by LefterisJP** [comment]
I already gave my opinion on the PR.

> Each node will know its balance and the balance of its counterparty so I still don't see the scenario where having the addresses in the signature is really required.

I don't see the need for being that explicit.

But I am not set on this. If both of you think it's fine I am gonna roll with it.
