### ISSUE TITLE
TokenNetwork - settleChannelFailSafe

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#77]
If something goes wrong in the Raiden client with the balance proofs sent to the contract for `closeChannel` and `updateNonClosingBalanceProof`, the channel cannot be settled anymore.

I am proposing an additional `settleChannelFailSafe` function. Nodes can sign again some data that fits the number of tokens that the channel has locked, callable only 1 time.

**Comment by LefterisJP** [comment]
> If something goes wrong in the Raiden client with the balance proofs sent to the contract for closeChannel and updateNonClosingBalanceProof

Can you define this a bit better? What do you envision going wrong? If the user closes with the wrong balance proof manually then he is to blame.

If the raiden client does not use the correct balance proof then it's a bug in our client. 

Adding yet another function to the smart contract to offer a mitigation for these 2 situations would complicate the protocol further. Is this really needed?

**Comment by loredanacirstea** [comment]
> If the raiden client does not use the correct balance proof then it's a bug in our client.

This is what I mean.

> Is this really needed?

I think enabling token recovery in case of a future bug in the Raiden client is a good idea. That's why I proposed it. But I pinged you and @hackaugusto to tell me if it's really needed.

**Comment by hackaugusto** [comment]
I don't see the point of this feature:

- If there is a bug and automatic settlement doesn't work, manual intervetion will be required
- If manual intervention is assumed, then either:
  - the client has the balance proof data persisted and properly validated, which is the whole point of the WAL architecture. In this case recovery is possbile, it can be in the form of a bugfix or manually using the availalble data.
  - the data is corrupt and no valid balance proof is available, therefor manual cooperation among the channel participants is required

I don't see how the proposed fallback could improve either case with manual intervention.

If the fallback is another automatic settlement code path, that is coded by the same people, on the same project, tested by the same test suite, I don't think it will be any less likely to contain bugs, it's just more code to be maintained and a larger surface area for bugs to occur.

**Comment by loredanacirstea** [comment]
The initial proposal was bad. It stemmed from seeing that `settleChannel` failed in a case, but this was due to a bad implementation in the contract. Opened https://github.com/raiden-network/raiden-contracts/issues/106 for this.

My question now is: does it make sense to allow `cooperativeSettle` to be called during the settlement window or after?
A worst case scenario would be: channel is closed with some balance proofs. There is a Raiden client update that contains a bug and we lose balance proof data (e.g. maybe nodes can agree on `transferred_amount`s, but we lose the pending transfers `locksroot` that was used to compute the balance proof). In case there is no way to retrieve the entire balance data (contract, MS have only the `balance_hash`es) in order to call `channelSettle`, the channel might remain locked.

**Comment by loredanacirstea** [comment]
This issue has been solved by making sure that the `settleChannel` function will never fail when called in the correct state (after the settlement window). 

Related commits:
https://github.com/raiden-network/raiden-contracts/commit/bf56d07c9207f7330e6c169d491cf560647e36df#diff-2f6fb78ac7aaf29aaec1ed8ab59468f8
https://github.com/raiden-network/raiden-contracts/commit/8decf565ff1098662c94b148cdb1b041aba6ee19#diff-2f6fb78ac7aaf29aaec1ed8ab59468f8
https://github.com/raiden-network/raiden-contracts/commit/044f6f6a7c62f4a77a40e18b8573daa0ee2a3cc5#diff-2f6fb78ac7aaf29aaec1ed8ab59468f8
