### ISSUE TITLE
RSB Deposit Contract

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/spec#79]
Prompted by [this](https://github.com/raiden-network/raiden-contracts/pull/37/files#r188252070) comment I open this issue to track our discussion on how we should keep the deposits of the RSB (Raiden Service Bundle) operators.

The RSB should have a single deposit per operator and not per service. So we will need another contract that would act as the deposit holder. And this contract would need to be linked to by all services (Monitoring, Pathfinding and Matrix home servers) in order to check if the user has "enough deposit" and to slash his deposit.

This could either be a single contract that would hold all deposits for all RSB operators or a contract that would control the creation and management of deed contracts, which would in turn hold the individual deposits (much like the ENS does).

Having a different contract holding each operator's deposit (the deed system) has the following advantages:

- A deed contract would be smaller, independent and with a small API. It can be tested and audited in isolation from the larger contract.
- Completely eliminates one category of bugs (user withdrawing funds greater than their deposit) 
- Easier to reason about

**Comment by karlb** [comment]
This is implemented in the form of the `UserDeposit` contract.
