### ISSUE TITLE
Settle on either `chain_id` or `network_id`

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#83]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md uses `chain_id`, but web3 & JSON RPC api use `network id` https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version.

Settle on one term and use it consistently across repos.

**Comment by palango** [comment]
No hard opinion on my side, Raiden mostly uses *network id*, in the contracts and libs we used *chain id*.

**Comment by karlb** [comment]
I've looked trough the spec repo and could not find usages of the term "network_id", anymore.
