### ISSUE TITLE
Add invariants for how the settlement amounts must be computed

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#86]
Check the conclusions from https://github.com/raiden-network/raiden-contracts/pull/123, and those obtained after solving https://github.com/raiden-network/raiden-contracts/issues/127 and clearly define the protocol used to compute the channel settlement amounts for each participant:
- all the values needed and what they stand for
- value constraints/invariants and who enforces them
- algorithm used to compute the amounts (not the Solidity implementation, we are not interested in the Solidity quirks - overflows and underflows, but in what the actual logic is when calculating the settlement balances)

Link all settlement computation issues & PRs as comments in this issue, to keep track of changes.

**Comment by loredanacirstea** [comment]
I am making a settlement algorithm analysis & attack vectors here: https://github.com/raiden-network/raiden-contracts/issues/188. It also contains some of the things that are supposed to be in the spec.

**Comment by jomuel** [comment]
Ok, I spent yesterday recovering & documenting the algorithm from the contract code. I'll see what needs to be rewritten.

**Comment by loredanacirstea** [comment]
@jomuel , that is perfect. Then please check that what I've written is correct. If you think the settlement algorithm should be different or you see differences between what you understood and what I've written, please document them.

**Comment by loredanacirstea** [comment]
I updated the description to make it more clear that the issue is not for describing the settlement algorithm as implemented in Solidity, but for explaining the settlement logic and value constraints.

This was unclear previously.
