### ISSUE TITLE
what's the shortcomming if  raiden cotracts must unlock before settle? 

### ISSUE THREAD

**Issue by nkbai** [raiden-network/spec#91]
node must unlock after channel settlement now.

what's the shortcomming  if raiden node must unlock HTLC before settlement?

I think there are two beneficialness : 
1. only one Token.Transfer for each participant
2. add some punishment mechanism  for dishonest mediated nodes 
 [add a way to punish the dishonest intermediate node](https://github.com/raiden-network/raiden-contracts/pull/35)
 even  the routing path selected by  path-finding-service may be error for some race condition.

**Comment by pirapira** [comment]
Unlock can only happen after the smart contract determines the Merkle hash root of the pending HTLC's .  In other words, after the channel settlement.
